-- DB에 추가 시 계정 추가
-- CREATE DATABASE boardproject;
-- CREATE USER 'songpa'@'%' IDENTIFIED BY  'songpa'; 
-- GRANT ALL PRIVILEGES ON boardproject.* TO 'songpa'@'%';

USE boardproject;

-- 기존 테이블 삭제
DROP TABLE IF EXISTS TBL_NOTICE;
DROP TABLE IF EXISTS TBL_ATTACHMENT;
DROP TABLE IF EXISTS TBL_REPLY;
DROP TABLE IF EXISTS TBL_BOARD;
DROP TABLE IF EXISTS TBL_MEMBER;
DROP TABLE IF EXISTS TBL_CATEGORY;

-- TABLE 생성
-- MEMBER 테이블 생성
CREATE TABLE TBL_MEMBER(
  MEMBER_NO INT AUTO_INCREMENT PRIMARY KEY,
  MEMBER_ID VARCHAR(20) UNIQUE,
  MEMBER_PWD VARCHAR(255) NOT NULL,
  NICKNAME VARCHAR(255) NOT NULL,
  PHONE VARCHAR(20),
  EMAIL VARCHAR(50),
  ADDRESS VARCHAR(255),
  ENROLL_DATE DATE,
  MEMBER_ROLE VARCHAR(15) DEFAULT 'ROLE_MEMBER' CHECK(MEMBER_ROLE IN ('ROLE_MEMBER', 'ROLE_ADMIN')),
  MEMBER_STATUS VARCHAR(2) DEFAULT 'Y'
);

-- 관리자 계정 추가(admin/admin)
INSERT INTO TBL_MEMBER (MEMBER_ID, MEMBER_PWD, NICKNAME, PHONE, EMAIL, MEMBER_ROLE) VALUES ('admin', '$2a$10$7NqnZ0pUQh2RDLDkcEmubOSWB2DSewpDNs7q7xwxgZHHvMgZGJ.rW', '관리자', '01012345678', 'admin@ohgiraffers.com', 'ROLE_ADMIN');
COMMIT;
-- 일반 계정 추가(test01/test01)
INSERT INTO TBL_MEMBER (MEMBER_ID, MEMBER_PWD, NICKNAME, PHONE, EMAIL, MEMBER_ROLE) VALUES ('test01', '$2a$10$WuQAYtpRG3hzY8nr98iFGuqsswJPyHTt/n/NSI5FCBbClTozsJg5C', '오지라퍼', '01012345678', 'test01@ohgiraffers.com', 'ROLE_MEMBER');
COMMIT;

-- 공지사항 테이블 생성
CREATE TABLE TBL_NOTICE(
  NOTICE_NO INT AUTO_INCREMENT PRIMARY KEY,
  NOTICE_TITLE VARCHAR(100) NOT NULL,
  NOTICE_BODY VARCHAR(4000) NOT NULL,
  NOTICE_WRITER_MEMBER_NO INT NOT NULL,
  NOTICE_COUNT INT DEFAULT 0,
  CREATED_DATE DATE,
  NOTICE_STATUS VARCHAR(1) DEFAULT 'Y',
  FOREIGN KEY (NOTICE_WRITER_MEMBER_NO) REFERENCES TBL_MEMBER (MEMBER_NO)
);

-- 카테고리 테이블 생성
CREATE TABLE TBL_CATEGORY(
  CATEGORY_CODE INT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(30) CHECK(CATEGORY_NAME IN('공통', '운동', '등산', '게임', '낚시', '요리', '기타'))  
);

-- 카테고리 테이블에 카테고리 추가
INSERT INTO TBL_CATEGORY (CATEGORY_NAME) VALUES('공통');
INSERT INTO TBL_CATEGORY (CATEGORY_NAME) VALUES('운동');
INSERT INTO TBL_CATEGORY (CATEGORY_NAME) VALUES('등산');
INSERT INTO TBL_CATEGORY (CATEGORY_NAME) VALUES('게임');
INSERT INTO TBL_CATEGORY (CATEGORY_NAME) VALUES('낚시');
INSERT INTO TBL_CATEGORY (CATEGORY_NAME) VALUES('요리');
INSERT INTO TBL_CATEGORY (CATEGORY_NAME) VALUES('기타');
COMMIT;

-- 게시판 테이블 생성
CREATE TABLE TBL_BOARD (
  BOARD_NO INT AUTO_INCREMENT PRIMARY KEY,
  BOARD_TYPE INT NOT NULL CHECK(BOARD_TYPE IN (1, 2)),
  CATEGORY_CODE INT,
  BOARD_TITLE VARCHAR(100),
  BOARD_BODY VARCHAR(4000) NOT NULL,
  BOARD_WRITER_MEMBER_NO INT NOT NULL,
  BOARD_COUNT INT DEFAULT 0 NOT NULL,
  CREATED_DATE DATE,
  MODIFIED_DATE DATE,
  BOARD_STATUS VARCHAR(1) DEFAULT 'Y',
  FOREIGN KEY (BOARD_WRITER_MEMBER_NO) REFERENCES TBL_MEMBER(MEMBER_NO),
  FOREIGN KEY (CATEGORY_CODE) REFERENCES TBL_CATEGORY(CATEGORY_CODE)
);

-- 게시물 샘플 추가
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '1 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '2 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '3 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '4 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '5 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '6 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '7 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '8 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '9 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '10 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '11 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '12 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '13 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '14 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '15 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '16 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '17 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '18 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '19 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '20 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '21 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '22 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '23 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '24 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '25 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '26 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '27 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '28 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '29 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '30 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '31 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '32 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '33 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '34 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '35 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '36 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '37 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '38 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '39 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '40 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '41 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '42 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '43 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '44 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '45 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '46 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '47 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '48 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '49 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '50 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '51 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '52 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '53 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '54 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '55 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '56 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '57 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '58 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '59 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '60 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '61 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '62 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '63 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '64 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '65 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '66 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '67 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '68 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '69 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '70 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '71 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '72 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '73 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '74 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '75 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '76 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '77 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '78 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '79 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '80 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '81 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '82 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '83 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '84 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '85 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '86 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '87 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '88 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '89 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '90 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '91 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '92 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '93 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '94 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '95 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '96 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '97 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '98 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '99 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '100 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '101 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '102 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '103 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '104 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '105 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '106 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '107 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '108 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '109 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '110 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '111 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '112 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '113 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '114 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '115 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '116 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '117 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '118 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '119 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '120 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '121 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '122 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);
INSERT INTO TBL_BOARD (BOARD_TYPE, CATEGORY_CODE, BOARD_TITLE, BOARD_BODY, BOARD_WRITER_MEMBER_NO)
VALUES (1, 1, '123 번째 게시물 입니다.', '내용은 없습니다. WE CAN DO IT!~', 2);

COMMIT;

-- REPLY 테이블 생성
CREATE TABLE TBL_REPLY (
  REPLY_NO INT AUTO_INCREMENT PRIMARY KEY,
  REF_BOARD_NO INT,
  REPLY_BODY VARCHAR(4000),
  REPLY_WRITER_MEMBER_NO INT,
  REPLY_STATUS VARCHAR(1) DEFAULT 'Y',
  CREATED_DATE DATE,
  FOREIGN KEY (REF_BOARD_NO) REFERENCES TBL_BOARD(BOARD_NO),
  FOREIGN KEY (REPLY_WRITER_MEMBER_NO) REFERENCES TBL_MEMBER(MEMBER_NO)
);

-- 첨부파일 테이블 생성
CREATE TABLE TBL_ATTACHMENT (
  ATTACHMENT_NO INT AUTO_INCREMENT PRIMARY KEY,
  REF_BOARD_NO INT NOT NULL,
  ORIGINAL_NAME VARCHAR(255) NOT NULL,
  SAVED_NAME VARCHAR(255) NOT NULL,
  SAVE_PATH VARCHAR(1000) NOT NULL,
  FILE_TYPE VARCHAR(5) CHECK(FILE_TYPE IN ('TITLE', 'BODY')),
  THUMBNAIL_PATH VARCHAR(255),
  ATTACHMENT_STATUS VARCHAR(1) DEFAULT 'Y',
  FOREIGN KEY (REF_BOARD_NO) REFERENCES TBL_BOARD(BOARD_NO)  
);
